### PR TITLE
Update GUI to fix the following:

### PR DESCRIPTION
**Pull request by random689**
Changes include

1. Prevent Tags from spilling over into the other details
2. Change ... in medical window to !!! to inform user that there are medical details for the student
3. Updated Involvement so that it will wrap downwards properly
4. Updated formClass so that it will not stretch along with involvement. 
5. Fix sizing for the MainWindow.fxml so that even at the smallest screen, the horizontal scroll bar will not be needed / will not show @nniiggeell Do check if this is ok 
6. Update sizing for Involvement, Class, Medical so that not one control the rest
7. Remove selected blue frame as it cannot be unselected (cannot fix this so just remove that feature)

Sample:

Tags when screen is small and screen is big (No more spilling over)
image

Form Class and Involvement are long but don't kill each other
image

Form class does not get stretched like before when involvement is very long
image

Medical Shows !!! if there is more lines after it
image
image

This is how "well" the GUI will be if its super abused when its long (left) and small (right)
image

@g4ryy u can just approve even if nigel haven checked yet cause that one is quite easy to change

Closes and fixes:
#208
#215

### CODE REVIEW

**Comment by random689** [comment]
Wait don't merge first i'm editing abit more stuff

**Comment by random689** [comment]
PLEASE BREAK THE GUI SO I CAN FIX IT CUZ I ALR TRIED BREAKING BUT PEOPLE STILL COULD BREAK IT IN PE D: THANKS

**Comment by nniiggeell** [comment]
i think this looks really good!!! 
So just to clarify, when will the medical become `!!!` ? is it if there is not enough space for the entire medical to be shown, then it will be truncated to (whatever it can show)!!! ?

**Comment by random689** [comment]
> 
> 
> i think this looks really good!!! So just to clarify, when will the medical become `!!!` ? is it if there is not enough space for the entire medical to be shown, then it will be truncated to (whatever it can show)!!! ?

Yes. so as long as there is medical for the student, the minimum it will show is `!!!` but if the size allows it to show its stuff, it will show as much as it can before it goes `!!!`

**Review by g4ryy — APPROVED** [review]
LGTM

**Pull request merged**
